### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [moghir2004/Musix-Player#2]
Hello, I would like to design a logo for your project. Do you have a logo? I can give some ideas if you are interested?
Greetings
Nuno

**Comment by moghir2004** [comment]
Nice man, I have some temporary one but already used. Any help would be great

**Comment by nunojesus** [comment]
Hello, can you send me your temporary logo? Do you want something special? Any demand?

Musix is the mix of the Music and Six words?

**Comment by moghir2004** [comment]
Musix is just Musics with different typo, man and make the logo **green** pls

**Comment by nunojesus** [comment]
Ok, I have to designs almost finish, I will try to send you today.

**Comment by nunojesus** [comment]
Hello, here is what I design.

The logo is a mix of the letters M and X, and also we can see the player button.

I Made 2 designs, if you like one just say it.

![musix-model](https://user-images.githubusercontent.com/34600369/39151583-8d77a384-473d-11e8-99f9-20d316ea91d9.png)

**Comment by nunojesus** [comment]
Im glad you like it, And the colours are good? 
Do you think it will be good in your app?
If there is everything good I wi all finish and make the files in png and other editable files.
Greetings

**Comment by moghir2004** [comment]
NO, The colors are excellent. I Like That Green And Yes Please Go Ahead And Post them so i can add them to the program

**Comment by nunojesus** [comment]
Hi, I saw that you merged my pull request, did you already used the logo, I would love to see it in the program or in other place, you could put it on the README file too.
Can you send me a snap to see it. 
Im sending you a link with all the files.
https://drive.google.com/drive/folders/10kCIjw7Rg4j3Yn2V9AHXGW9Fhz2XWCBQ?usp=sharing
